### ISSUE TITLE
Unexpected override behaviour

### ISSUE THREAD

**Issue by snclever** [Kodein-Framework/Kodein-DI#100]
By accident I stumbled upon some wired behavior when extending a Kodein instance and overriding its dependencies. I created a minimal failing test to demonstrate it:
```
    data class Foo(val name: String)
    data class Bar(val foo: Foo)

    fun root() = Kodein {
        bind<Foo>() with singleton { Foo("rootFoo") }
        bind<Bar>() with singleton { Bar(instance()) }
    }

    fun sub(root: Kodein) = Kodein {
        extend(root, allowOverride = true)

        bind<Foo>(overrides = true) with singleton {
            val overriddenInstance = overriddenInstance() as Foo
            overriddenInstance.copy(name ="subFoo")
        }
        bind<Bar>(overrides = true) with singleton {
            val overriddenInstance = overriddenInstance() as Bar
            overriddenInstance.copy(foo = instance())
        }
    }

    val root = root()
    val sub = sub(root)

    val subFoo : Foo = sub.instance()
    val rootFoo : Foo = root.instance()

    assertEquals("subFoo", subFoo.name)
    assertEquals("rootFoo", rootFoo.name)

    val subBar : Bar = sub.instance()
    val rootBar : Bar = root.instance()

    assertEquals("subFoo", subBar.foo.name)
    assertEquals("rootFoo", rootBar.foo.name) // <- fails
```

The important part here is the order in which we retrieve the Bar instances. If we first retrieve Bar from root and then from sub everything works as expected.

I suspect that using overriddenInstance() in the second binding of Bar somehow leaks the overridden Foo instance into the creation process of root Bar.

**Comment by SalomonBrys** [comment]
Wooooow...
I'll have a look at that.
Thanks a lot for the report :)

**Comment by SalomonBrys** [comment]
So... you have pointed somewhat a monster of an issue...

The test can be further simplified as thus:

        data class Foo(val name: String)
        data class Bar(val foo: Foo)

        val root = Kodein {
            bind<Foo>() with provider { Foo("rootFoo") }
            bind<Bar>() with singleton { Bar(instance()) }
        }.direct

        val sub = Kodein {
            extend(root, allowOverride = true)
            bind<Foo>(overrides = true) with provider { Foo("subFoo") }
        }.direct

        val subBar : Bar = sub.instance()
        val rootBar : Bar = root.instance()

        assertEquals("subFoo", subBar.foo.name)
        assertEquals("rootFoo", rootBar.foo.name) // <- fails

Because `Bar` is bound with a `singleton`, it will be constructed only once, and then reused everytime. Therefore, the first construction defines the instance.
But `Foo` is bound to different values whether retrieved from `root` or `sub`. So the first container used to access `Bar` does define the instance used in *both* container, as is the purpose of `extend`.
I am working on a fix for version 5.0. It will be a breaking change, and add some DSL.
It will be part of Beta 2. I will post here once I have released it.

**Comment by SalomonBrys** [comment]
Kodein 5.0 beta2 has been released.

This issue was, by far, the main update :)

You should read the [Overridden access from parent section of the documentation](https://salomonbrys.github.io/Kodein/?5.0/core#_overridden_access_from_parent) as it explains the new behaviour (that might differ from what you were expecting).

I will close this issue when Kodein 5.0 is released.

**Comment by SalomonBrys** [comment]
Kodein 5.0 stable has been released :)
