### ISSUE TITLE
Overriding method should call super.onCreate

### ISSUE THREAD

**Issue by sysint64** [Kodein-Framework/Kodein-DI#101]
Hello, I'm just starting using Kodein in my android project. All works fine, but Android Sudio marks method `onCreate` as an error for this code:
```Kotlin
class LoginActivity : KodeinAppCompatActivity(), LoginView {
    private val presenter: LoginPresenter by with(this).instance()

    override fun onCreate(savedInstanceState: Bundle?) {  // Error here
        super.onCreate(savedInstanceState)
        presenter.onStart()
    }
}
```

**Comment by exallium** [comment]
+1 for this error.

This appears to be happening because Android Studio isn't reading the sources file properly.  I can see that it is downloaded successfully (in ~/.gradle/cache/...) but it doesn't appear in AS.

Kodein sources work normally otherwise, so far it's only the Android Sources for this lib that don't seem to appear.

Decompiling I can see that the super.onCreate is called properly, but AS can't automatically detect that.  It goes down one level and sees compiled code, and pops the error up anyhow.

Building compiles successfully and runs successfully as expected, but it's annoying to see this error popping up.

**Comment by SalomonBrys** [comment]
The `KodeinAppCompatActivity` does not exists anymore in [Kodein 5.0 beta](https://salomonbrys.github.io/Kodein/?5.0).
I will close this issue once the stable 5.0 will be released.

**Comment by eygraber** [comment]
For correctness' sake, this is a [Lint](https://issuetracker.google.com/issues/67035929) bug, not related to Kodein.
