### ISSUE TITLE
"Fallback" for missing bindings/Resolving bindings at runtime

### ISSUE THREAD

**Issue by adriantodt** [Kodein-Framework/Kodein-DI#132]
Hi, I'm migrating from Guice to Kodein, and I reached the following issue:

I used Guice primarily alongside Reflections to do classpath scanning + dependency injection to build all the Commands.

Honestly, it'd be honestly impossible to build all the commands (see below) without binding resolving them at runtime.

After porting my DI code to Kodein, I reached a ``org.kodein.di.Kodein$NotFoundException: No binding found for bind<ColorCommand>() with ? { ? }``, and then I realized that Kodein does not resolve that on runtime.

Currently, I'm using a fork of the Kodein JX to build all the commands using Kodein at runtime but I wanted to ask for a way to add "custom default fallback resolving" so that we can, before throwing a "binding not found", check if the fallback resolving can attempt baking it on runtime.

I know it's a slow and rather lazy solution but it'd add new possibilities of extensions.

Suggestion:

```
Kodein {
    // ... static bindings

    // register a fallback binding function
    onNotFound { // something useful here as args like Kodein or the container and the not-found binding
        // throws if can't runtime-bake the binding
        // returns the binding (and registers that binding on the container)
    }
}
```

It'd help people who wants to hack the Kodein to it's 100% and also it'd enable more stuff on the `JSR-330` api implementation (like building an entire dep tree on runtime)

------

My Commands' File Tree:
![image](https://user-images.githubusercontent.com/6955035/40661950-5e6b39f2-632b-11e8-8efe-6b0cc7bb688b.png)

**Comment by SalomonBrys** [comment]
There is, it is called `externalSource`.
Because you asked, I just saw that I forgot to document this feature. Sorry about that, I'll document it ASAP.

In the meantime, you can see it used in this test: https://github.com/Kodein-Framework/Kodein-DI/blob/master/generic/kodein-di-generic-jvm/src/test/kotlin/org/kodein/di/test/GenericJvmTests.kt#L1278

Basically, you can set the `externalSource` property to an `ExternalSource` instance, which is a SAM interface that you can implement with a lambda with the `ExternalSource { }` constructor.
The lambda is called every time a new `Key` is asked but not found. The `Key` itself contains information about the binding that was asked but not found. (see https://github.com/Kodein-Framework/Kodein-DI/blob/master/core/kodein-di-core-common/src/main/kotlin/org/kodein/di/Kodein.kt#L71)
The `externalSource` function will be called **only once** per unknown key. This function must return itself a function (which you can easily create with the `externalFactory` function) that takes an `Any?` argument and returns the instance. This lambda will be called **everytime** an instance is requested. Note that if no argument is provided, the argument to the lambda will be `Unit`.

Hope this helps ;)

**Comment by SalomonBrys** [comment]
There you go.

Actually, it was already documented... in the "Advanced usage" document... that nobody knew existed :stuck_out_tongue: 
This document has been merged back into the main core documentation.

The documentation of external source is here: http://kodein.org/Kodein-DI/?5.1/core#_add_an_external_source
