### ISSUE TITLE
AndroidLifecycleScope doesn't work

### ISSUE THREAD

**Issue by BulatMukhutdinov** [Kodein-Framework/Kodein-DI#136]
I use kodein 5.1.0 and kotlin 1.2.50. I am trying to provide my VIewModel. To do this I am using AndroidLifecycleScope<Activity> but my view model isn't injected. Error is
`org.kodein.di.Kodein$NotFoundException: No binding found for bind<MyViewModel>() with ? { ? }
Available bindings for this type:
        bind<MyViewModel>() with scoped(AndroidLifecycleScope.multiItem).singleton { MyViewModel }
Registered in this Kodein container:
        bind<MyViewModel>() with scoped(AndroidLifecycleScope.multiItem).singleton { MyViewModel }
`

Here is sample project
https://github.com/BulatMukhutdinov/KodeinSample

Pls help me to find out where is the issue
Thanks

**Comment by SalomonBrys** [comment]
First of all, you should not use `AndroidLifecycleScope<MainActivity>()` but `AndroidLifecycleScope<AppCompatActivity>()`

When you use scopes, you need to provide the context so that Kodein can find the scope.

Here, the context is the `AppCompatActivity` since you are using `AndroidLifecycleScope<AppCompatActivity>()`.

You, in your `MainActivity`, you should provide the context:

```
override val kodeinContext = kcontext<AppCompatActivity>(this)
```

I understand that this is not properly documented. I'll fix that ;)

**Comment by BulatMukhutdinov** [comment]
Thank you! You just saved me!
