### ISSUE TITLE
Dependency injection by type alias

### ISSUE THREAD

**Issue by raderio** [Kodein-Framework/Kodein-DI#147]
Have you analyzed implementing Dependency injection by type alias?
```
object RedisCache { }
typealias Cache = RedisCache
```
If we need to change it
```
object MongoCache { }
typealias Cache = MongoCache
```
It is done in compile time

**Comment by SalomonBrys** [comment]
This is not a solution, because:

- There are a lot of features of Kodein that can only exist at runtime.
- Kodein cannot use code generation because it only exists for JVM (& Kodein is a multi-platform project)
- DI is a lot more than assigning an implementation. It's about order of initialisation, transitive dependencies, scoping, etc.
