### ISSUE TITLE
custom sharedpreference

### ISSUE THREAD

**Issue by sagarnayak** [Kodein-Framework/Kodein-DI#234]
I want to create my shared preference singleton with a name defined by me. how can I do that?

**Comment by romainbsl** [comment]
Hello,

If you're using an android module for Kodein https://kodein.org/Kodein-DI/?6.3/android.
You should have access to a factory for `SharedPreferences`. Thus, you can do the following:

```kotlin
val factoryPreferences: SharedPreferences by instance(arg = "MyPref")
factoryPreferences.getBoolean("key_bool", true)
```

**Comment by sagarnayak** [comment]
I am injecting like this - 

val preference: SharedPreferences by instance(arg = "customPref")

 bind() from singleton { Repository(instance(), preference, instance(), instance()) }

and injecting the preference into the Repository. Am I doing it right?

**Comment by romainbsl** [comment]
You could. IMO, I don't like mixing binding and retrieving.
In fact, I don't think this will work because Kodein will try to resolve the dependencies before the end of the configuration phase.

If you just need a singleton you can do it like:

```kotlin
bind<Repository>() with singleton {
      val pref: SharedPreferences by this.kodein.instance(arg = "customPref")
      Repository(pref)
}
```

Or if you need a different Repository depending on the SharedPreferences you can do something like that:

```kotlin
bind<Repository>() with factory {preferences: SharedPreferences -> 
        Repository(instance(), preferences, instance(), instance())
}
``` 
And then on call site you can do this:
```kotlin
val pref: SharedPreferences by factory(arg = "customPref")
val repository: Repository by instance(arg = pref)
```

**Comment by sagarnayak** [comment]
that will do. thanks for your time.
