### ISSUE TITLE
using kodein in non-context-class

### ISSUE THREAD

**Issue by DaveBoy** [Kodein-Framework/Kodein-DI#239]
```  
class MyController(androidContext: Context) : KodeinAware {
    override val kodein by androidContext.closestKodein()
    override val kodeinContext = kcontext(androidContext)
    val inflater: LayoutInflater by instance()
  }  
```

but i can‘t find the context.closestKodein() in the '6.0.1'
and i can‘t find the sample of it in [Kodein-DI/demo/demo-android/](https://github.com/Kodein-Framework/Kodein-DI/tree/5.2/demo/demo-android)
this is what i import
```
   implementation 'org.kodein.di:kodein-di-generic-jvm:6.0.1'
    implementation 'org.kodein.di:kodein-di-framework-android-x:6.0.1'
    implementation 'org.kodein.di:kodein-di-framework-android-core:6.0.1'
```

**Comment by romainbsl** [comment]
Hi,

Demos are now in the project https://github.com/Kodein-Framework/Kodein-Samples
You'll find the android demo here https://github.com/Kodein-Framework/Kodein-Samples/tree/master/di/coffee-maker/android

According to the `closestKodein` code you cannot call it as an extension on `androidContext`, in fact it depends on the real type of the context. 

However, in your case you can call the `closestKodein` (`kodein()`since 6.1) by using:

> fun closestKodein(context: Context)

```kotlin
override val kodein by closestKodein(androidContext)
```

**Comment by DaveBoy** [comment]
ok,tks for your answer
