### ISSUE TITLE
Support for Providers

### ISSUE THREAD

**Issue by IRus** [Kodein-Framework/Kodein-DI#270]
Use case:

```
class MetricsServiceProvider(
    private val configuration: Configuration,
    private val shutdownManager: ShutdownManager
) : Provider<MetricsService> {
    ovveride fun get(): MetricsService {
        //.. code that initializes and setups MetricsService
    }
}
```

I moved service initialization in class with dependencies, I'd like to do something like this:

```
bind<MetricsService>() with provider<MetricsServiceProvider>()
```

right now, only way is:

```
bind<MetricsService>() with singleton { MetricsServiceProvider(instance(), instance()).get() }
```

This is common pattern in [guice](https://github.com/google/guice/wiki/ProviderBindings)/[spring](https://docs.spring.io/spring-javaconfig/docs/1.0.0.M4/reference/html/ch02s02.html).

**Comment by romainbsl** [comment]
Hellom now I do remember why we could not do that at the moment.

Guice and Spring are heavily using code reflection to build their DAGm but as we are targeting Kotlin/Multiplatform we have an issue, Kotlin/Native and Kotlin/JS has no such thing as reflection, so we cannot define dependencies, without explicitly declare their inputsm that's why we need the `instance()` function.

We will "soon" be able to change that, but until JetBrains does provide a public API for Compiler Plugins (after 1.4 apparently), we are stuck.

**Comment by romainbsl** [comment]
But if you have don't have any need to target other platforms than the JVM we have a module for you:, the one that implement the JSR330

https://kodein.org/Kodein-DI/?6.5/jsr330

**Comment by romainbsl** [comment]
Close the issue, as it can't be done right now.
An alternative with singleton would be to use the `init { }` block. As dependencies are resolved lazily it has the same behaviour as the first example.
