### ISSUE TITLE
Recursion exceptions after update

### ISSUE THREAD

**Issue by MitsuraIvan** [Kodein-Framework/Kodein-DI#373]
Hey there, update gone wild on my side

```
class C1(di: DIAware) {
    private val c2 by di.instance<C2>()

    fun call() {
        c2.test()
    }
}
```

```
class C2(di: DIAware) {
    private val c1 by di.instance<C1>()

    fun test() {
        Log.d("log_tag", "piu")
    }

    fun call() {
        c1.call()
    }
}
```

```
fun kekw() {

    val kodein = DI {
        bind<C1>() with singleton { C1(di) }
        bind<C2>() with singleton { C2(di) }
    }

    val c2 by kodein.instance<C2>()
    c2.call()
}
```

     Caused by: org.kodein.di.DI$DependencyLoopException: Dependency recursion:
         bind<C2>
        ╔╩>bind<C1>
        ║  ╚>bind<C2>
        ╚════╝
        
Gradle:       
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-bin.zip
classpath "com.android.tools.build:gradle:7.0.0-beta03"

kotlin 1.5.10

kodein updated to 7.6.0 from 7.1.0-master-88. Should work absolutely fine, C2 already exists, C1 should get his reference with no issues, why loop tho, am I missing something?

**Comment by MitsuraIvan** [comment]
I did a little research, 7.1 works great, 7.2 and any future versions crashing

**Comment by romainbsl** [comment]
Indeed, this is a regression. We need to investigate to sort this out. We'll keep you posted.

**Comment by romainbsl** [comment]
After some investigation, this happens because we change the way we handle the context of our bindings. 
By default, we no longer have a context attached to our bindings, thus they are considered as global.

Your case worked before, because we were automatically attaching the context while retrieving a binding, thus there were no dependency loop. Therefore, now that there is no context attached, both binding are consider has global and the container consider that they can't be retrieved from each other.

These changes have been done to fix a memory leak that we were chasing for multiple months !!! So we probably won't go back on this. 

But we still have to consider your use case. By defining your classes C1 and C2 as DIAware, it will attached itself as a context to the binding.
So the following snippet works perfectly on *Kodein-DI 7.6*:

```kotlin
class C1(override val di: DI) : DIAware {
    private val c2 : C2 by instance()
    fun test() = println(c2)
    fun call() = c2.test()
}
class C2(override val di: DI) : DIAware {
    private val c1 : C1 by instance()
    fun test() = c1.test()
    fun call() = c1.call()
}

fun main(args: Array<String>) {
    val di = DI {
        bind<C1>() with singleton { C1(di) }
        bind<C2>() with singleton { C2(di) }
    }

    val c2 by di.instance<C2>()
    c2.call()
}
```

Finally, I'm curious, why is your use case that your classes need to reference each other ?
