### ISSUE TITLE
Proposing: Some better code readability and reducing boilerplate

### ISSUE THREAD

**Issue by dinbtechit** [Kodein-Framework/Kodein-DI#411]
Proposing: Some better code readability and reducing boilerplate. (inspired by Spring style annotations)

Make any class as `@Injectable`
```
@Injectable(scope = "singleton | factory")
class Engine {
  fun start () { . . .}
}
```
**usage:**
```
class Car ( private engine: Engine ) {                      // Automatically Inject the dependency
  fun start() {
    engine.start() 
  }
}
```

It's worth mentioning..  I have no idea if this is even feasible. So looking for some suggestions.

**Comment by romainbsl** [comment]
We don't want that kind of "automagical" dependency injection for Kodein-DI.

1. Because it is implicit that you loose control over your DI. This is why Kodein-DI was born, to overcome the complexity of Dagger from Android, thus we prefer an explicit API.
2. Because annotations processing was not possible in Kotlin Multiplatform until recently.

For now, we will not consider such feature, but we will work to make the API simpler and even more readable.
